// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utility.Authority.Infrastructure;

namespace Utility.Authority.Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20190530082849_lj20190530")]
    partial class lj20190530
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");
#pragma warning restore 612, 618
        }
    }
}
